//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financas.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoriaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoriaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Financas.Domain.Resources.CategoriaResources", typeof(CategoriaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Não Encontrada!.
        /// </summary>
        public static string CategoriaNaoEncontrada {
            get {
                return ResourceManager.GetString("CategoriaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta é uma categoria principal, existem subcategorias vinculadas!.
        /// </summary>
        public static string CategoriaVinculadas {
            get {
                return ResourceManager.GetString("CategoriaVinculadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria não pode ser excluída, existem despesas vinculados!.
        /// </summary>
        public static string DespesasVinculadas {
            get {
                return ResourceManager.GetString("DespesasVinculadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Obrigatório!.
        /// </summary>
        public static string IdObrigatorio {
            get {
                return ResourceManager.GetString("IdObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria não pode ser excluída, existem lançamentos vinculados!.
        /// </summary>
        public static string LancamentosVinculados {
            get {
                return ResourceManager.GetString("LancamentosVinculados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Duplicado!.
        /// </summary>
        public static string NomeDuplicado {
            get {
                return ResourceManager.GetString("NomeDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Obrigatório!.
        /// </summary>
        public static string NomeObrigatorio {
            get {
                return ResourceManager.GetString("NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Tamanho Inválido!.
        /// </summary>
        public static string NomeTamanhoInvalido {
            get {
                return ResourceManager.GetString("NomeTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria não pode ser excluída, existem orçamentos vinculados!.
        /// </summary>
        public static string OrcamentosVinculados {
            get {
                return ResourceManager.GetString("OrcamentosVinculados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Obrigatório!.
        /// </summary>
        public static string TipoObrigatorio {
            get {
                return ResourceManager.GetString("TipoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Tamanho Inválido!.
        /// </summary>
        public static string TipoTamanhoInvalido {
            get {
                return ResourceManager.GetString("TipoTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente o usuário que efetuou o cadastro pode efetuar esta operação!.
        /// </summary>
        public static string UsuarioCadastroInvalido {
            get {
                return ResourceManager.GetString("UsuarioCadastroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Obrigatório!.
        /// </summary>
        public static string UsuarioObrigatorio {
            get {
                return ResourceManager.GetString("UsuarioObrigatorio", resourceCulture);
            }
        }
    }
}
