//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financas.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DespesaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DespesaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Financas.Domain.Resources.DespesaResources", typeof(DespesaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Duplicado!.
        /// </summary>
        public static string DescricaoDuplicado {
            get {
                return ResourceManager.GetString("DescricaoDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Obrigatório!.
        /// </summary>
        public static string DescricaoObrigatorio {
            get {
                return ResourceManager.GetString("DescricaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Tamanho Inválido!.
        /// </summary>
        public static string DescricaoTamanhoInvalido {
            get {
                return ResourceManager.GetString("DescricaoTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Obrigatório!.
        /// </summary>
        public static string IdObrigatorio {
            get {
                return ResourceManager.GetString("IdObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria não pode ser excluída, existem lançamentos vinculados!.
        /// </summary>
        public static string LancamentosVinculados {
            get {
                return ResourceManager.GetString("LancamentosVinculados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente o usuário que efetuou o cadastro pode efetuar esta operação!.
        /// </summary>
        public static string UsuarioCadastroInvalido {
            get {
                return ResourceManager.GetString("UsuarioCadastroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Obrigatório!.
        /// </summary>
        public static string UsuarioObrigatorio {
            get {
                return ResourceManager.GetString("UsuarioObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Obrigatório!.
        /// </summary>
        public static string ValorObrigatorio {
            get {
                return ResourceManager.GetString("ValorObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimento Obrigatório!.
        /// </summary>
        public static string VenctoObrigatorio {
            get {
                return ResourceManager.GetString("VenctoObrigatorio", resourceCulture);
            }
        }
    }
}
